export const COUNTRIES: string[] = [
  'Argentina',
  'Australia',
  'Austria',
  'Bélgica',
  'Bolivia',
  'Brasil',
  'Canadá',
  'Chile',
  'China',
  'Colombia',
  'Corea del Sur',
  'Costa Rica',
  'Cuba',
  'Dinamarca',
  'Ecuador',
  'Egipto',
  'El Salvador',
  'Emiratos Árabes Unidos',
  'Escocia',
  'Eslovenia',
  'España',
  'Estados Unidos',
  'Filipinas',
  'Finlandia',
  'Francia',
  'Grecia',
  'Guatemala',
  'Hungría',
  'India',
  'Indonesia',
  'Irlanda',
  'Islandia',
  'Israel',
  'Italia',
  'Japón',
  'Marruecos',
  'México',
  'Noruega',
  'Nueva Zelanda',
  'Panamá',
  'Paraguay',
  'Perú',
  'Polonia',
  'Portugal',
  'Reino Unido',
  'República Dominicana',
  'Rumania',
  'Singapur',
  'Sudáfrica',
  'Suecia',
  'Suiza',
  'Tailandia',
  'Turquía',
  'Uruguay',
  'Venezuela',
  'Vietnam'
];
